name: CI

on:
  push:    
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: xcodebuild clean build -project BerkananLite.xcodeproj -scheme BerkananLite -destination "platform=macOS"
